<?xml version="1.0" encoding="utf-8"?><Database Name="GoogleDocsTest" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=l-fj2dkv1;Initial Catalog=GoogleDocsTest;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GoogleDocsTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Backup" Member="tbl_Backups">
    <Type Name="tbl_Backup">
      <Column Name="BackupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Doc_tbl_Backup" Member="tbl_Doc" ThisKey="DocID" OtherKey="ID" Type="tbl_Doc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Docs" Member="tbl_Docs">
    <Type Name="tbl_Doc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocID" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="DocPath" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="IsShared" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSharedOutside" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSharedOrgWide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ACL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="WebContentLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="WebViewLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="IsWritersCanShare" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThumbnailLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="QuotaBytesUsed" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Parents" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Owners" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="OrignalFileName" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="IconLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="FileExtension" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="ExportableLinks" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="ExplicitlyTrashed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ETag" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="EmbedLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Editable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DownloadUrl" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="AppDataContent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AlternateLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Kind" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="PermissionListID" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Association Name="tbl_Doc_tbl_Backup" Member="tbl_Backups" ThisKey="ID" OtherKey="DocID" Type="tbl_Backup" />
      <Association Name="tbl_Doc_tbl_Permission" Member="tbl_Permissions" ThisKey="ID" OtherKey="DocID" Type="tbl_Permission" />
      <Association Name="tbl_User_tbl_Doc" Member="tbl_User" ThisKey="OwnerID" OtherKey="UserID" Type="tbl_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Permissions" Member="tbl_Permissions">
    <Type Name="tbl_Permission">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalRoles" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="AuthKey" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="ETag" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="PermissionID" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Kind" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="PhotoLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="SelfLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="WithLink" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Association Name="tbl_Doc_tbl_Permission" Member="tbl_Doc" ThisKey="DocID" OtherKey="ID" Type="tbl_Doc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Users" Member="tbl_Users">
    <Type Name="tbl_User">
      <Column Name="UserID" Type="System.String" DbType="VarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsStudent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DomainSharingPolicy" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="ETag" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="IsCurrentAppInstalled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Kind" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="LargestChangeID" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="PermissionID" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="QuotaBytesTotal" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="QuotaBytesUsed" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="QuotaBytesUsedAggregate" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="QuotaBytesUsedInTrash" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RootFolderID" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Association Name="tbl_User_tbl_Doc" Member="tbl_Docs" ThisKey="UserID" OtherKey="OwnerID" Type="tbl_Doc" />
    </Type>
  </Table>
</Database>