#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GOPROGO")]
public partial class SearchDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public SearchDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GOPROGOConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public SearchDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SearchDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SearchDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SearchDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<vwSearchEnt> vwSearchEnts
	{
		get
		{
			return this.GetTable<vwSearchEnt>();
		}
	}
	
	public System.Data.Linq.Table<vwDemandSearchEnt> vwDemandSearchEnts
	{
		get
		{
			return this.GetTable<vwDemandSearchEnt>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.ProfileByCategoryAndCityID")]
	public ISingleResult<vwSearchEnt> ProfileByCategoryAndCityID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID, cityID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(4)));
		return ((ISingleResult<vwSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.ProfileSearchCategory")]
	public ISingleResult<vwSearchEnt> ProfileSearchCategory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(512)")] string criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria, categoryID, cityID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(5)));
		return ((ISingleResult<vwSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.ProfileSearchDistance")]
	public ISingleResult<vwSearchEnt> ProfileSearchDistance([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(512)")] string criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lat", DbType="Float")] System.Nullable<double> lat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Long", DbType="Float")] System.Nullable<double> @long, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsKM", DbType="Bit")] System.Nullable<bool> isKM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria, lat, @long, isKM, cityID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(7)));
		return ((ISingleResult<vwSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.ProfileSearchMain")]
	public ISingleResult<vwSearchEnt> ProfileSearchMain([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(512)")] string criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria, cityID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(4)));
		return ((ISingleResult<vwSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.ProfileSearchName")]
	public ISingleResult<vwSearchEnt> ProfileSearchName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(64)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(64)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, lastName, cityID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(5)));
		return ((ISingleResult<vwSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.DemandSearchMain")]
	public ISingleResult<vwDemandSearchEnt> DemandSearchMain([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(512)")] string criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria, cityID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(4)));
		return ((ISingleResult<vwDemandSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.DemandByCityIDAndCategoryID")]
	public ISingleResult<vwDemandSearchEnt> DemandByCityIDAndCategoryID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cityID, categoryID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(4)));
		return ((ISingleResult<vwDemandSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.DemandByCityIDAndCategoryIDAndDemandTypeID")]
	public ISingleResult<vwDemandSearchEnt> DemandByCityIDAndCategoryIDAndDemandTypeID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DemandTypeID", DbType="Int")] System.Nullable<int> demandTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cityID, categoryID, demandTypeID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(5)));
		return ((ISingleResult<vwDemandSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.DemandSearchCategory")]
	public ISingleResult<vwDemandSearchEnt> DemandSearchCategory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(512)")] string criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria, cityID, categoryID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(5)));
		return ((ISingleResult<vwDemandSearchEnt>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="SEARCH.DemandSearchDemandType")]
	public ISingleResult<vwDemandSearchEnt> DemandSearchDemandType([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criteria", DbType="NVarChar(512)")] string criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityID", DbType="Int")] System.Nullable<int> cityID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DemandTypeID", DbType="Int")] System.Nullable<int> demandTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageNum", DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRowCount", DbType="Int")] ref System.Nullable<int> totalRowCount)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteria, cityID, demandTypeID, pageNum, pageSize, totalRowCount);
		totalRowCount = ((System.Nullable<int>)(result.GetParameterValue(5)));
		return ((ISingleResult<vwDemandSearchEnt>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="SEARCH.vwSearchEnt")]
public partial class vwSearchEnt
{
	
	private System.Nullable<int> _CityID;
	
	private System.Nullable<int> _SexID;
	
	private System.Nullable<int> _RegionID;
	
	private System.Nullable<int> _CountryID;
	
	private System.Nullable<int> _CategoryID;
	
	private System.Nullable<int> _Currency_CountryID;
	
	private System.Nullable<int> _JobUnitID;
	
	private string _FirstName;
	
	private string _LastName;
	
	private string _Slogan;
	
	private string _AddressLine1;
	
	private string _AddressLine2;
	
	private string _ProfileDescription;
	
	private System.Nullable<decimal> _MinimumRate;
	
	private System.Nullable<double> _Longitude;
	
	private System.Nullable<double> _Latitude;
	
	private string _SmallProfilePicture;
	
	private string _Website;
	
	private int _ID;
	
	private System.Nullable<int> _ReviewCount;
	
	private System.Nullable<decimal> _ReviewScore;
	
	private string _CategoryName;
	
	private string _JobUnitName;
	
	private string _MembershipTypeName;
	
	private string _SexName;
	
	private string _CurrencyCode;
	
	private string _Country;
	
	private string _City;
	
	private string _Region;
	
	private decimal _Distance;
	
	public vwSearchEnt()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityID", DbType="Int")]
	public System.Nullable<int> CityID
	{
		get
		{
			return this._CityID;
		}
		set
		{
			if ((this._CityID != value))
			{
				this._CityID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexID", DbType="Int")]
	public System.Nullable<int> SexID
	{
		get
		{
			return this._SexID;
		}
		set
		{
			if ((this._SexID != value))
			{
				this._SexID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
	public System.Nullable<int> RegionID
	{
		get
		{
			return this._RegionID;
		}
		set
		{
			if ((this._RegionID != value))
			{
				this._RegionID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="Int")]
	public System.Nullable<int> CountryID
	{
		get
		{
			return this._CountryID;
		}
		set
		{
			if ((this._CountryID != value))
			{
				this._CountryID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
	public System.Nullable<int> CategoryID
	{
		get
		{
			return this._CategoryID;
		}
		set
		{
			if ((this._CategoryID != value))
			{
				this._CategoryID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency_CountryID", DbType="Int")]
	public System.Nullable<int> Currency_CountryID
	{
		get
		{
			return this._Currency_CountryID;
		}
		set
		{
			if ((this._Currency_CountryID != value))
			{
				this._Currency_CountryID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobUnitID", DbType="Int")]
	public System.Nullable<int> JobUnitID
	{
		get
		{
			return this._JobUnitID;
		}
		set
		{
			if ((this._JobUnitID != value))
			{
				this._JobUnitID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(64)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(64)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slogan", DbType="NVarChar(128)")]
	public string Slogan
	{
		get
		{
			return this._Slogan;
		}
		set
		{
			if ((this._Slogan != value))
			{
				this._Slogan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="NVarChar(256)")]
	public string AddressLine1
	{
		get
		{
			return this._AddressLine1;
		}
		set
		{
			if ((this._AddressLine1 != value))
			{
				this._AddressLine1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine2", DbType="NVarChar(256)")]
	public string AddressLine2
	{
		get
		{
			return this._AddressLine2;
		}
		set
		{
			if ((this._AddressLine2 != value))
			{
				this._AddressLine2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileDescription", DbType="NVarChar(1024)")]
	public string ProfileDescription
	{
		get
		{
			return this._ProfileDescription;
		}
		set
		{
			if ((this._ProfileDescription != value))
			{
				this._ProfileDescription = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumRate", DbType="Money")]
	public System.Nullable<decimal> MinimumRate
	{
		get
		{
			return this._MinimumRate;
		}
		set
		{
			if ((this._MinimumRate != value))
			{
				this._MinimumRate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
	public System.Nullable<double> Longitude
	{
		get
		{
			return this._Longitude;
		}
		set
		{
			if ((this._Longitude != value))
			{
				this._Longitude = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
	public System.Nullable<double> Latitude
	{
		get
		{
			return this._Latitude;
		}
		set
		{
			if ((this._Latitude != value))
			{
				this._Latitude = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallProfilePicture", DbType="VarChar(512)")]
	public string SmallProfilePicture
	{
		get
		{
			return this._SmallProfilePicture;
		}
		set
		{
			if ((this._SmallProfilePicture != value))
			{
				this._SmallProfilePicture = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(1024)")]
	public string Website
	{
		get
		{
			return this._Website;
		}
		set
		{
			if ((this._Website != value))
			{
				this._Website = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewCount", DbType="Int")]
	public System.Nullable<int> ReviewCount
	{
		get
		{
			return this._ReviewCount;
		}
		set
		{
			if ((this._ReviewCount != value))
			{
				this._ReviewCount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewScore", DbType="Decimal(18,2) NOT NULL")]
	public System.Nullable<decimal> ReviewScore
	{
		get
		{
			return this._ReviewScore;
		}
		set
		{
			if ((this._ReviewScore != value))
			{
				this._ReviewScore = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(256)")]
	public string CategoryName
	{
		get
		{
			return this._CategoryName;
		}
		set
		{
			if ((this._CategoryName != value))
			{
				this._CategoryName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobUnitName", DbType="NVarChar(255)")]
	public string JobUnitName
	{
		get
		{
			return this._JobUnitName;
		}
		set
		{
			if ((this._JobUnitName != value))
			{
				this._JobUnitName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipTypeName", DbType="NVarChar(64)")]
	public string MembershipTypeName
	{
		get
		{
			return this._MembershipTypeName;
		}
		set
		{
			if ((this._MembershipTypeName != value))
			{
				this._MembershipTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexName", DbType="NVarChar(25)")]
	public string SexName
	{
		get
		{
			return this._SexName;
		}
		set
		{
			if ((this._SexName != value))
			{
				this._SexName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCode", DbType="NVarChar(255)")]
	public string CurrencyCode
	{
		get
		{
			return this._CurrencyCode;
		}
		set
		{
			if ((this._CurrencyCode != value))
			{
				this._CurrencyCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(255)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(255)")]
	public string Region
	{
		get
		{
			return this._Region;
		}
		set
		{
			if ((this._Region != value))
			{
				this._Region = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Decimal(4,4) NOT NULL")]
	public decimal Distance
	{
		get
		{
			return this._Distance;
		}
		set
		{
			if ((this._Distance != value))
			{
				this._Distance = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="SEARCH.vwDemandSearchEnt")]
public partial class vwDemandSearchEnt
{
	
	private int _ID;
	
	private System.Nullable<int> _CityID_Location;
	
	private System.Nullable<int> _RegionID_Location;
	
	private System.Nullable<int> _CountryID_Location;
	
	private int _CategoryID;
	
	private System.Nullable<int> _CountryID_CurrencyCode;
	
	private int _ProfileID;
	
	private int _DemandTypeID;
	
	private System.Nullable<int> _JobUnitID;
	
	private string _Title;
	
	private string _DescriptionPlainText;
	
	private System.DateTime _CreatedDate;
	
	private System.DateTime _EndTime;
	
	private System.Nullable<int> _OfferCount;
	
	private string _TimeConstraint;
	
	private bool _IsAnonymousOffer;
	
	private System.Nullable<decimal> _MinBudget;
	
	private System.Nullable<decimal> _MaxBudget;
	
	private string _CityName;
	
	private string _RegionName;
	
	private string _CountryName;
	
	private string _CurrencyCode;
	
	private string _CategoryName;
	
	private string _DemandTypeName;
	
	private string _JobUnit;
	
	public vwDemandSearchEnt()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityID_Location", DbType="Int")]
	public System.Nullable<int> CityID_Location
	{
		get
		{
			return this._CityID_Location;
		}
		set
		{
			if ((this._CityID_Location != value))
			{
				this._CityID_Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID_Location", DbType="Int")]
	public System.Nullable<int> RegionID_Location
	{
		get
		{
			return this._RegionID_Location;
		}
		set
		{
			if ((this._RegionID_Location != value))
			{
				this._RegionID_Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID_Location", DbType="Int")]
	public System.Nullable<int> CountryID_Location
	{
		get
		{
			return this._CountryID_Location;
		}
		set
		{
			if ((this._CountryID_Location != value))
			{
				this._CountryID_Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int NOT NULL")]
	public int CategoryID
	{
		get
		{
			return this._CategoryID;
		}
		set
		{
			if ((this._CategoryID != value))
			{
				this._CategoryID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID_CurrencyCode", DbType="Int")]
	public System.Nullable<int> CountryID_CurrencyCode
	{
		get
		{
			return this._CountryID_CurrencyCode;
		}
		set
		{
			if ((this._CountryID_CurrencyCode != value))
			{
				this._CountryID_CurrencyCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileID", DbType="Int NOT NULL")]
	public int ProfileID
	{
		get
		{
			return this._ProfileID;
		}
		set
		{
			if ((this._ProfileID != value))
			{
				this._ProfileID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DemandTypeID", DbType="Int NOT NULL")]
	public int DemandTypeID
	{
		get
		{
			return this._DemandTypeID;
		}
		set
		{
			if ((this._DemandTypeID != value))
			{
				this._DemandTypeID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobUnitID", DbType="Int")]
	public System.Nullable<int> JobUnitID
	{
		get
		{
			return this._JobUnitID;
		}
		set
		{
			if ((this._JobUnitID != value))
			{
				this._JobUnitID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this._Title = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionPlainText", DbType="NVarChar(4000)")]
	public string DescriptionPlainText
	{
		get
		{
			return this._DescriptionPlainText;
		}
		set
		{
			if ((this._DescriptionPlainText != value))
			{
				this._DescriptionPlainText = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this._CreatedDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime NOT NULL")]
	public System.DateTime EndTime
	{
		get
		{
			return this._EndTime;
		}
		set
		{
			if ((this._EndTime != value))
			{
				this._EndTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfferCount", DbType="Int")]
	public System.Nullable<int> OfferCount
	{
		get
		{
			return this._OfferCount;
		}
		set
		{
			if ((this._OfferCount != value))
			{
				this._OfferCount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeConstraint", DbType="NVarChar(128)")]
	public string TimeConstraint
	{
		get
		{
			return this._TimeConstraint;
		}
		set
		{
			if ((this._TimeConstraint != value))
			{
				this._TimeConstraint = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymousOffer", DbType="Bit NOT NULL")]
	public bool IsAnonymousOffer
	{
		get
		{
			return this._IsAnonymousOffer;
		}
		set
		{
			if ((this._IsAnonymousOffer != value))
			{
				this._IsAnonymousOffer = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinBudget", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> MinBudget
	{
		get
		{
			return this._MinBudget;
		}
		set
		{
			if ((this._MinBudget != value))
			{
				this._MinBudget = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxBudget", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> MaxBudget
	{
		get
		{
			return this._MaxBudget;
		}
		set
		{
			if ((this._MaxBudget != value))
			{
				this._MaxBudget = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityName", DbType="NVarChar(255)")]
	public string CityName
	{
		get
		{
			return this._CityName;
		}
		set
		{
			if ((this._CityName != value))
			{
				this._CityName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionName", DbType="NVarChar(255)")]
	public string RegionName
	{
		get
		{
			return this._RegionName;
		}
		set
		{
			if ((this._RegionName != value))
			{
				this._RegionName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="NVarChar(255)")]
	public string CountryName
	{
		get
		{
			return this._CountryName;
		}
		set
		{
			if ((this._CountryName != value))
			{
				this._CountryName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCode", DbType="NVarChar(255)")]
	public string CurrencyCode
	{
		get
		{
			return this._CurrencyCode;
		}
		set
		{
			if ((this._CurrencyCode != value))
			{
				this._CurrencyCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(256)")]
	public string CategoryName
	{
		get
		{
			return this._CategoryName;
		}
		set
		{
			if ((this._CategoryName != value))
			{
				this._CategoryName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DemandTypeName", DbType="NVarChar(64)")]
	public string DemandTypeName
	{
		get
		{
			return this._DemandTypeName;
		}
		set
		{
			if ((this._DemandTypeName != value))
			{
				this._DemandTypeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobUnit", DbType="NVarChar(255)")]
	public string JobUnit
	{
		get
		{
			return this._JobUnit;
		}
		set
		{
			if ((this._JobUnit != value))
			{
				this._JobUnit = value;
			}
		}
	}
}
#pragma warning restore 1591
